version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hr_portal_db
    environment:
      POSTGRES_DB: hr_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hr_portal_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hr_portal_backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: hr_portal
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - hr_portal_network
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hr_portal_frontend
    ports:
      - "3001:3001"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - hr_portal_network
    command: npm run dev

volumes:
  postgres_data:

networks:
  hr_portal_network:
    driver: bridge